# Generated by Django 3.1 on 2020-08-14 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200814_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='hist_deptos',
            field=models.ManyToManyField(related_name='hist_pessoa_depto', to='app.Departamento'),
        ),
    ]
