# Generated by Django 3.1 on 2020-08-18 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_pessoa_depto_chefia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='pessoa',
            name='nacionalidade',
            field=models.CharField(default='teste', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='hist_salarios',
            field=models.ManyToManyField(related_name='hist_pessoa_salario', to='app.Salario'),
        ),
    ]
