# Generated by Django 3.1 on 2020-08-18 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200818_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='senioridade',
            field=models.CharField(choices=[('T', 'Trainee'), ('J', 'Júnior'), ('P', 'Pleno'), ('S', 'Sênior')], default='T', max_length=1),
        ),
    ]
